name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)-$(Build.SourceBranchName)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - main
  tags:
    exclude:
      - '*'
      
variables:
  - group: ApiKeys
  - name: solutionFile
    value: 'Octo.Sdk.sln'
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}
  - name: buildConfiguration
    value: 'Release'
  - name: buildPlatform
    value: 'any cpu'
  - name: MajorVersion
    value: '0'
  - name: MinorVersion
    value: '1'
    
stages:
 - stage: Build
   jobs:
    - job: buildsdk
      displayName: "Build nuget and execute tests"
      pool:
        name: Gerald-Local-Linux
      steps:
      - template: update-build-number.yml
      - checkout: self
        clean: true
        submodules: true
      - template: set-version.yml
      - template: download-ca.yml        
      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: 'build'
          projects:  $(SolutionFile)
          arguments: '--configuration $(BuildConfiguration) /p:OctoNugetPrivateServer=$(nugetPrivateServer)'
          publishWebProjects: false
          zipAfterPublish: false
          modifyOutputPath: false
      - task: DotNetCoreCLI@2
        displayName: 'Test'
        inputs:
          command: 'test'
          arguments: '--configuration $(buildConfiguration) /p:OctoNugetPrivateServer=$(nugetPrivateServer)'
          projects: |
            **/*Tests.csproj
            !**/*SystemTests.csproj
          testRunTitle: 'CI'
      - template: build-and-push-docker-image.yml
        parameters:
          Repository: meshmakers/octo-communication-adapter-simulation
          Dockerfile: src/Sdk.Plug.Simulation/Dockerfile
          IsRelease: ${{ variables.isRelease }}          
      - task: PowerShell@2
        inputs:
          filePath: '$(System.DefaultWorkingDirectory)/devops-build/createDocumentation.ps1'
          arguments: '-configuration $(buildConfiguration)'
        displayName: 'Create documentation'
      - task: PublishSymbols@2
        displayName: Publish symbols path
        continueOnError: True
        inputs:
          SearchPattern: '**\bin\**\*.pdb'
          PublishSymbols: false
          SymbolServerType: TeamServices
      - task: CopyFiles@2
        displayName: 'Copy Files from **/*.nupkg to $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: $(Build.SourcesDirectory)
          Contents: |
            **/*.nupkg
            bin/**/documentation/**/*.*
          TargetFolder: $(build.artifactstagingdirectory)
      - task: PowerShell@2
        displayName: 'Create versioninfo file'
        inputs:
          targetType: 'inline'
          script: |
              New-Item $(build.artifactstagingdirectory)/versioninfo.txt
              Set-Content $(build.artifactstagingdirectory)/versioninfo.txt $(Build.BuildNumber)
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: local'
        inputs:
          ArtifactName: local
      - template: push-nuget-package.yml           

