using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;
using Meshmakers.Octo.ConstructionKit.Contracts.Services;

namespace Meshmakers.Octo.Sdk.SourceGeneration;

/// <summary>
///     Generates code for a CK type
/// </summary>
public class CkEnumCodeGenerator
{
    /// <summary>
    ///     Returns the singleton instance of <see cref="CkEnumCodeGenerator" />
    /// </summary>
    public static readonly CkEnumCodeGenerator Instance = new();

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return obj is CkEnumCodeGenerator;
    }

    public bool Equals(CkEnumCodeGenerator? other)
    {
        return other is CkEnumCodeGenerator;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return GetType().GetHashCode();
    }

    public string Generate(string ns, CkModelId modelId, CkEnumDto ckEnumDto, string cacheTenantId, ICkCacheService cacheService)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit enum {ckEnumDto.EnumId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public enum Rt{ckEnumDto.EnumId.Name.MakeClassName()}Enum");
        sb.AppendLine("{");
        foreach (var ckSelectionValueDto in ckEnumDto.Values)
        {
            if (!string.IsNullOrWhiteSpace(ckSelectionValueDto.Description))
            {
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {ckSelectionValueDto.Description}");
                sb.AppendLine("    /// </summary>");
            }

            sb.AppendLine($"    {ckSelectionValueDto.Name} = {ckSelectionValueDto.Key},");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}