using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;
using Meshmakers.Octo.ConstructionKit.Contracts.Services;

namespace Meshmakers.Octo.Sdk.SourceGeneration;

/// <summary>
///     Generates code for a CK type
/// </summary>
public class CkTypeCodeGenerator : ICkTypeCodeGenerator
{
    /// <summary>
    ///     Returns the singleton instance of <see cref="CkTypeCodeGenerator" />
    /// </summary>
    public static readonly CkTypeCodeGenerator Instance = new();

    /// <inheritdoc />
    public bool Equals(ICkTypeCodeGenerator? other)
    {
        return other is CkTypeCodeGenerator;
    }

    /// <inheritdoc />
    public string Generate(string ns, CkModelId modelId, CkTypeDto ckType, string cacheTenantId, ICkCacheService cacheService)
    {
        string ckBaseType;
        if (ckType.DerivedFromCkTypeId != null)
        {
            ckBaseType = $" : Rt" +
                         $"{ckType.DerivedFromCkTypeId.Key.TypeId.MakeClassName()}Dto";
        }
        else
        {
            ckBaseType = ": QlRtEntityDtoWithAssociations";
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.Communication.Contracts.DataTransferObjects;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit data transfer type {ckType.TypeId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class Rt{ckType.TypeId.TypeId.MakeClassName()}Dto{ckBaseType}");
        sb.AppendLine("{");
        if (ckType.Attributes != null)
        {
            foreach (var ckTypeAttributeDto in ckType.Attributes)
            {
                var ckAttributeGraph = cacheService.GetCkAttribute(cacheTenantId, ckTypeAttributeDto.CkAttributeId);
                if (!string.IsNullOrWhiteSpace(ckAttributeGraph.Description))
                {
                    sb.AppendLine("  /// <summary>");
                    sb.AppendLine($"  /// {ckAttributeGraph.Description}");
                    sb.AppendLine("  /// </summary>");
                }

                if (ckTypeAttributeDto.IsOptional)
                {
                    AttributeCodeGenerator.GenerateNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph);
                }
                else
                {
                    AttributeCodeGenerator.GenerateNonNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph);
                }
            }
        }

        if (ckType.Associations != null)
        {
            foreach (var ckTypeAssociationDto in ckType.Associations)
            {
                GenerateNavigation(ckTypeAssociationDto, sb, cacheTenantId, cacheService);
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return obj is CkTypeCodeGenerator;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return GetType().GetHashCode();
    }

    private void GenerateNavigation(CkTypeAssociationDto ckTypeAssociationDto, StringBuilder sb, string cacheTenantId,
        ICkCacheService cacheService)
    {
        //var ckAssociationRoleGraph = cacheService.GetCkAssociationRole(cacheTenantId, ckTypeAssociationDto.CkRoleId);

        sb.AppendLine($"  // Unsupported by Generator: {ckTypeAssociationDto.CkRoleId}->{ckTypeAssociationDto.TargetCkTypeId}");
    }
}