using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;
using Meshmakers.Octo.ConstructionKit.Contracts.Services;

namespace Meshmakers.Octo.Sdk.SourceGeneration;

/// <summary>
///     Generates code for mutation DTO's
/// </summary>
public class MutationDtoCodeGenerator : IMutationDtoCodeGenerator
{
    /// <summary>
    ///     Returns the singleton instance of <see cref="MutationDtoCodeGenerator" />
    /// </summary>
    public static readonly MutationDtoCodeGenerator Instance = new();

    /// <inheritdoc />
    public bool Equals(IMutationDtoCodeGenerator? other)
    {
        return other is MutationDtoCodeGenerator;
    }

    /// <inheritdoc />
    public string GenerateType(string ns, CkTypeDto ckType, string cacheTenantId, ICkCacheService cacheService)
    {
        string ckBaseType = string.Empty;
        if (ckType.DerivedFromCkTypeId != null)
        {
            ckBaseType = $" : Rt" +
                         $"{ckType.DerivedFromCkTypeId.Key.TypeId.MakeClassName()}Dto";
        }
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using Meshmakers.Octo.Communication.Contracts.DataTransferObjects;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit data transfer type {ckType.TypeId.FullName} for mutation operations");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class Rt{ckType.TypeId.TypeId.MakeClassName()}MutationDto{ckBaseType}");
        sb.AppendLine("{");
        if (ckType.Attributes != null)
        {
            foreach (var ckTypeAttributeDto in ckType.Attributes)
            {
                var ckAttributeGraph = cacheService.GetCkAttribute(cacheTenantId, ckTypeAttributeDto.CkAttributeId);
                if (!string.IsNullOrWhiteSpace(ckAttributeGraph.Description))
                {
                    sb.AppendLine("  /// <summary>");
                    sb.AppendLine($"  /// {ckAttributeGraph.Description}");
                    sb.AppendLine("  /// </summary>");
                }

                sb.AppendLine("  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]");
                AttributeCodeGenerator.GenerateNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph, true);
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    public string GenerateRecord(string ns, CkRecordDto ckRecord, string cacheTenantId, ICkCacheService cacheService)
    {
        string ckRecordBaseType = string.Empty;
        if (ckRecord.DerivedFromCkRecordId != null)
        {
            ckRecordBaseType = $" : Rt" +
                         $"{ckRecord.DerivedFromCkRecordId.Key.RecordId.MakeClassName()}RecordMutationDto";
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using Meshmakers.Octo.Communication.Contracts.DataTransferObjects;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit data transfer record {ckRecord.RecordId.FullName} for mutation operations");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class Rt{ckRecord.RecordId.RecordId.MakeClassName()}RecordMutationDto{ckRecordBaseType}");
        sb.AppendLine("{");
        if (ckRecord.Attributes != null)
        {
            foreach (var ckTypeAttributeDto in ckRecord.Attributes)
            {
                var ckAttributeGraph = cacheService.GetCkAttribute(cacheTenantId, ckTypeAttributeDto.CkAttributeId);
                if (!string.IsNullOrWhiteSpace(ckAttributeGraph.Description))
                {
                    sb.AppendLine("  /// <summary>");
                    sb.AppendLine($"  /// {ckAttributeGraph.Description}");
                    sb.AppendLine("  /// </summary>");
                }

                sb.AppendLine("  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]");
                AttributeCodeGenerator.GenerateNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph, true);
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return obj is QueryDtoCodeGenerator;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return GetType().GetHashCode();
    }

}