using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;
using Meshmakers.Octo.ConstructionKit.Contracts.DependencyGraph;
using Meshmakers.Octo.ConstructionKit.Contracts.Services;

namespace Meshmakers.Octo.Sdk.SourceGeneration;

/// <summary>
///     Generates code for query DTO's
/// </summary>
public class QueryDtoCodeGenerator : IQueryDtoCodeGenerator
{
    /// <summary>
    ///     Returns the singleton instance of <see cref="QueryDtoCodeGenerator" />
    /// </summary>
    public static readonly QueryDtoCodeGenerator Instance = new();

    /// <inheritdoc />
    public bool Equals(IQueryDtoCodeGenerator? other)
    {
        return other is QueryDtoCodeGenerator;
    }

    /// <inheritdoc />
    public string GenerateType(string ns, CkTypeDto ckType, string cacheTenantId, ICkCacheService cacheService)
    {
        string ckBaseType;
        if (ckType.DerivedFromCkTypeId != null)
        {
            ckBaseType = $" : Rt" +
                         $"{ckType.DerivedFromCkTypeId.ElementId.Name.MakeClassName()}Dto";
        }
        else
        {
            ckBaseType = ": QlRtEntityDtoWithAssociations";
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.Communication.Contracts.DataTransferObjects;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit data transfer type {ckType.TypeId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class Rt{ckType.TypeId.Name.MakeClassName()}Dto{ckBaseType}");
        sb.AppendLine("{");
        if (ckType.Attributes != null)
        {
            foreach (var ckTypeAttributeDto in ckType.Attributes)
            {
                var ckAttributeGraph = cacheService.GetCkAttribute(cacheTenantId, ckTypeAttributeDto.CkAttributeId);
                if (!string.IsNullOrWhiteSpace(ckAttributeGraph.Description))
                {
                    sb.AppendLine("  /// <summary>");
                    sb.AppendLine($"  /// {ckAttributeGraph.Description}");
                    sb.AppendLine("  /// </summary>");
                }
                // In GraphQL, we do not have non-nullable properties,
                // because everything can be selected and is therefore nullable,
                // The only known optimization would be during the creation of a new object,
                // where we can use non-nullable properties
                AttributeCodeGenerator.GenerateNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph, false);
            }
        }

        if (ckType.Associations != null)
        {
            foreach (var ckTypeAssociationDto in ckType.Associations)
            {
                GenerateNavigation(ckTypeAssociationDto, sb, cacheTenantId, cacheService);
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    ///     Generates a GraphQL <c>ObjectGraphType</c> for the stream-data projection of a CK type.
    ///     Only emitted when the type has at least one <c>isDataStream</c> attribute.
    ///     Returns an empty string when no stream-data attributes are present.
    /// </summary>
    public string GenerateSdDtoType(string ns, CkTypeDto ckType, string cacheTenantId, ICkCacheService cacheService)
    {
        if (ckType.Attributes == null)
        {
            return string.Empty;
        }

        var dataStreamAttributes = ckType.Attributes
            .Select(a => (Dto: a, Graph: cacheService.GetCkAttribute(cacheTenantId, a.CkAttributeId)))
            .Where(x => x.Graph.IsDataStream)
            .ToList();

        if (dataStreamAttributes.Count == 0)
        {
            return string.Empty;
        }

        var typeName = ckType.TypeId.Name.MakeClassName();

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using GraphQL.Types;");
        sb.AppendLine("using Meshmakers.Octo.ConstructionKit.Contracts;");
        sb.AppendLine("using Meshmakers.Octo.Runtime.Contracts.StreamData;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// GraphQL stream-data projection type generated from construction kit type {ckType.TypeId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class Sd{typeName}DtoType : ObjectGraphType<Sd{typeName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public Sd{typeName}DtoType()");
        sb.AppendLine("    {");
        sb.AppendLine($"        Name = \"Sd{typeName}\";");
        sb.AppendLine($"        Description = \"Stream-data projection of {typeName}\";");
        sb.AppendLine("        Field(d => d.RtId, typeof(OctoObjectIdType));");
        sb.AppendLine("        Field(d => d.CkTypeId, typeof(RtCkIdGraph<CkTypeId>));");
        sb.AppendLine("        Field(d => d.Timestamp, typeof(DateTimeGraphType));");
        sb.AppendLine("        Field(d => d.RtWellKnownName, true);");
        sb.AppendLine("        Field(d => d.RtCreationDateTime, typeof(DateTimeGraphType));");
        sb.AppendLine("        Field(d => d.RtChangedDateTime, typeof(DateTimeGraphType));");

        foreach (var (dto, graph) in dataStreamAttributes)
        {
            var graphType = MapAttributeValueTypeToGraphQlType(graph.ValueType);
            sb.AppendLine($"        Field(d => d.{dto.AttributeName}, typeof({graphType}), nullable: true);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string MapAttributeValueTypeToGraphQlType(AttributeValueTypesDto valueType)
    {
        return valueType switch
        {
            AttributeValueTypesDto.String => "StringGraphType",
            AttributeValueTypesDto.StringArray => "ListGraphType<StringGraphType>",
            AttributeValueTypesDto.Int => "IntGraphType",
            AttributeValueTypesDto.IntArray => "ListGraphType<IntGraphType>",
            AttributeValueTypesDto.Int64 => "LongGraphType",
            AttributeValueTypesDto.Double => "DecimalGraphType",
            AttributeValueTypesDto.Boolean => "BooleanGraphType",
            AttributeValueTypesDto.DateTime => "DateTimeGraphType",
            AttributeValueTypesDto.DateTimeOffset => "DateTimeOffsetGraphType",
            AttributeValueTypesDto.TimeSpan => "TimeSpanSecondsGraphType",
            _ => "StringGraphType"
        };
    }

    public string GenerateRecord(string ns, CkRecordDto ckRecord, string cacheTenantId, ICkCacheService cacheService)
    {
        string ckBaseRecord = string.Empty;
        if (ckRecord.DerivedFromCkRecordId != null)
        {
            ckBaseRecord = $" : Rt" +
                           $"{ckRecord.DerivedFromCkRecordId.ElementId.Name.MakeClassName()}RecordDto";
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.Communication.Contracts.DataTransferObjects;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit data transfer record {ckRecord.RecordId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class Rt{ckRecord.RecordId.Name.MakeClassName()}RecordDto{ckBaseRecord}");
        sb.AppendLine("{");
        if (ckRecord.Attributes != null)
        {
            foreach (var ckTypeAttributeDto in ckRecord.Attributes)
            {
                var ckAttributeGraph = cacheService.GetCkAttribute(cacheTenantId, ckTypeAttributeDto.CkAttributeId);
                if (!string.IsNullOrWhiteSpace(ckAttributeGraph.Description))
                {
                    sb.AppendLine("  /// <summary>");
                    sb.AppendLine($"  /// {ckAttributeGraph.Description}");
                    sb.AppendLine("  /// </summary>");
                }
                // In GraphQL, we do not have non-nullable properties,
                // because everything can be selected and is therefore nullable,
                // The only known optimization would be during the creation of a new object,
                // where we can use non-nullable properties
                AttributeCodeGenerator.GenerateNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph, false);
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return obj is QueryDtoCodeGenerator;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return GetType().GetHashCode();
    }

    private void GenerateNavigation(CkTypeAssociationDto ckTypeAssociationDto, StringBuilder sb, string cacheTenantId,
        ICkCacheService cacheService)
    {
        //var ckAssociationRoleGraph = cacheService.GetCkAssociationRole(cacheTenantId, ckTypeAssociationDto.CkRoleId);

        sb.AppendLine(
            $"  // Unsupported by Generator: {ckTypeAssociationDto.CkRoleId}->{ckTypeAssociationDto.TargetCkTypeId}");
    }
}