using System.Text;
using Meshmakers.Octo.ConstructionKit.Contracts;
using Meshmakers.Octo.ConstructionKit.Contracts.DataTransferObjects;
using Meshmakers.Octo.ConstructionKit.Contracts.Services;

namespace Meshmakers.Octo.Sdk.SourceGeneration;

/// <summary>
///     Generates code for query DTO's
/// </summary>
public class QueryDtoCodeGenerator : IQueryDtoCodeGenerator
{
    /// <summary>
    ///     Returns the singleton instance of <see cref="QueryDtoCodeGenerator" />
    /// </summary>
    public static readonly QueryDtoCodeGenerator Instance = new();

    /// <inheritdoc />
    public bool Equals(IQueryDtoCodeGenerator? other)
    {
        return other is QueryDtoCodeGenerator;
    }

    /// <inheritdoc />
    public string GenerateType(string ns, CkTypeDto ckType, string cacheTenantId, ICkCacheService cacheService)
    {
        string ckBaseType;
        if (ckType.DerivedFromCkTypeId != null)
        {
            ckBaseType = $" : Rt" +
                         $"{ckType.DerivedFromCkTypeId.ElementId.Name.MakeClassName()}Dto";
        }
        else
        {
            ckBaseType = ": QlRtEntityDtoWithAssociations";
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.Communication.Contracts.DataTransferObjects;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit data transfer type {ckType.TypeId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class Rt{ckType.TypeId.Name.MakeClassName()}Dto{ckBaseType}");
        sb.AppendLine("{");
        if (ckType.Attributes != null)
        {
            foreach (var ckTypeAttributeDto in ckType.Attributes)
            {
                var ckAttributeGraph = cacheService.GetCkAttribute(cacheTenantId, ckTypeAttributeDto.CkAttributeId);
                if (!string.IsNullOrWhiteSpace(ckAttributeGraph.Description))
                {
                    sb.AppendLine("  /// <summary>");
                    sb.AppendLine($"  /// {ckAttributeGraph.Description}");
                    sb.AppendLine("  /// </summary>");
                }
                // In GraphQL, we do not have non-nullable properties,
                // because everything can be selected and is therefore nullable,
                // The only known optimization would be during the creation of a new object,
                // where we can use non-nullable properties
                AttributeCodeGenerator.GenerateNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph, false);
            }
        }

        if (ckType.Associations != null)
        {
            foreach (var ckTypeAssociationDto in ckType.Associations)
            {
                GenerateNavigation(ckTypeAssociationDto, sb, cacheTenantId, cacheService);
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    public string GenerateRecord(string ns, CkRecordDto ckRecord, string cacheTenantId, ICkCacheService cacheService)
    {
        string ckBaseRecord = string.Empty;
        if (ckRecord.DerivedFromCkRecordId != null)
        {
            ckBaseRecord = $" : Rt" +
                           $"{ckRecord.DerivedFromCkRecordId.ElementId.Name.MakeClassName()}RecordDto";
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Meshmakers.Octo.Communication.Contracts.DataTransferObjects;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated from construction kit data transfer record {ckRecord.RecordId.FullName}");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public partial class Rt{ckRecord.RecordId.Name.MakeClassName()}RecordDto{ckBaseRecord}");
        sb.AppendLine("{");
        if (ckRecord.Attributes != null)
        {
            foreach (var ckTypeAttributeDto in ckRecord.Attributes)
            {
                var ckAttributeGraph = cacheService.GetCkAttribute(cacheTenantId, ckTypeAttributeDto.CkAttributeId);
                if (!string.IsNullOrWhiteSpace(ckAttributeGraph.Description))
                {
                    sb.AppendLine("  /// <summary>");
                    sb.AppendLine($"  /// {ckAttributeGraph.Description}");
                    sb.AppendLine("  /// </summary>");
                }
                // In GraphQL, we do not have non-nullable properties,
                // because everything can be selected and is therefore nullable,
                // The only known optimization would be during the creation of a new object,
                // where we can use non-nullable properties
                AttributeCodeGenerator.GenerateNullableProperty(ckTypeAttributeDto, sb, ckAttributeGraph, false);
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return obj is QueryDtoCodeGenerator;
    }

    /// <inheritdoc />
    public override int GetHashCode()
    {
        return GetType().GetHashCode();
    }

    private void GenerateNavigation(CkTypeAssociationDto ckTypeAssociationDto, StringBuilder sb, string cacheTenantId,
        ICkCacheService cacheService)
    {
        //var ckAssociationRoleGraph = cacheService.GetCkAssociationRole(cacheTenantId, ckTypeAssociationDto.CkRoleId);

        sb.AppendLine(
            $"  // Unsupported by Generator: {ckTypeAssociationDto.CkRoleId}->{ckTypeAssociationDto.TargetCkTypeId}");
    }
}